services:
  habit_tracker1:
    container_name: habit_tracker1
    build: .
    command: ["web", 
      "python3", "-m",
      "gunicorn", "-b", "0.0.0.0:8000", 
      "Config.wsgi:application", 
      "--workers", "2",
      "--reload"
      ]
    # it's for debug
    volumes:
      - .:/app
    ports:
      - 80:8000
    depends_on:
      - postgres_primary
      # - postgres_replica
      - redis

  habit_tracker2:
    container_name: habit_tracker2
    build: .
    command: ["web", 
      "python3", "-m",
      "gunicorn", "-b", "0.0.0.0:8000", 
      "Config.wsgi:application", 
      "--workers", "2",
      "--reload"
      ]
    # it's for debug
    volumes:
      - .:/app
    ports:
      - 80:8000
    depends_on:
      - postgres_primary
      # - postgres_replica
      - redis

  habit_tracker3:
    container_name: habit_tracker3
    build: .
    command: ["web", 
      "python3", "-m",
      "gunicorn", "-b", "0.0.0.0:8000", 
      "Config.wsgi:application", 
      "--workers", "2",
      "--reload"
      ]
    # it's for debug
    volumes:
      - .:/app
    ports:
      - 80:8000
    depends_on:
      - postgres_primary
      # - postgres_replica
      - redis

  postgres_primary:
    container_name: postgres_primary
    image: postgres
    volumes:
      - postgres_pri_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  postgres_replica:
    container_name: postgres_replica
    image: postgres
    volumes:
      - postgres_rep_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "$$REDIS_PASSWORD"]


volumes:
  postgres_pri_data:
  postgres_rep_data:
  redis_data: